services:
  reservations:
    build:
      context: .
      dockerfile: apps/reservations/Dockerfile
      target: development
    command: pnpm run start:dev reservations
    env_file:
      - apps/reservations/.env
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    restart: always
  auth:
    build:
      context: .
      dockerfile: apps/auth/Dockerfile
      target: development
    command: pnpm run start:dev auth
    restart: always
    env_file:
      - apps/auth/.env
    ports:
      - 3001:3001
    volumes:
      - .:/usr/src/app
  payments:
    build:
      context: .
      dockerfile: apps/payments/Dockerfile
      target: development
    command: pnpm run start:dev payments
    env_file:
      - apps/payments/.env
    restart: always
    volumes:
      - .:/usr/src/app
  notifications:
    build:
      context: .
      dockerfile: apps/notifications/Dockerfile
      target: development
    command: pnpm run start:dev notifications
    restart: always
    env_file:
      - apps/notifications/.env
    volumes:
      - .:/usr/src/app
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
